# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 09:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slides',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(max_length=10)),
                ('file_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=400)),
            ],
        ),
        migrations.AddField(
            model_name='slides',
            name='slides',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataStructuresAndAlgorithms.Topics'),
        ),
    ]
